version: "3"
services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - "MYSQL_ROOT_PASSWORD="
    ports:
      - "3306:3306"
    volumes:
      - "/Users/regip/Documents/eclipse-workspace/mysql:/var/lib/mysql"